name: n8n
version: 2025.11.2
slug: hass-addons-n8n
description: Run n8n instance on Home Assistant
url: https://github.com/racksync/hass-addons-suite/tree/main/n8n
hassio_api: true
hassio_role: default
homeassistant: 2025.11.0
panel_icon: mdi:transit-connection-variant
advanced: true
homeassistant_api: true
apparmor: true
backup: cold #  the supervisor turns the add-on off before taking a backup
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
icon: icon.png
logo: icon.png
webui: "http://[HOST]:[PORT:5678]"
map:
  - ssl:ro
  - backup:ro
  - share:ro
  - media:rw
  - config:ro
watchdog: "http://[HOST]:[PORT:5678]"
ingress: true
ingress_port: 5690
ports:
  "5678/tcp": 5678
  "5690/tcp": null
ports_description:
  "5678/tcp": n8n main port (direct access for webhooks),
  "5690/tcp": The port for main n8n UI via nginx reverse proxy.
options:
  timezone: Asia/Bangkok
  n8n_host: 127.0.0.1
  n8n_port: 5678
  webhook_url: ""
  n8n_editor_base_url: ""
  n8n_path: ""
  n8n_metrics: false
  n8n_block_env_access_in_node: false
  n8n_git_node_disable_bare_repos: true
  n8n_trust_proxy: true
  n8n_protocol: http
  n8n_log_level: info
  db_sqlite_pool_size: 10
  env_vars_list: []
  cmd_line_args: ""
schema:
  timezone: str
  n8n_host: str?
  n8n_port: int
  webhook_url: str?
  n8n_editor_base_url: str?
  n8n_path: str?
  n8n_metrics: bool?  
  n8n_block_env_access_in_node: bool?
  n8n_git_node_disable_bare_repos: bool?
  n8n_trust_proxy: bool?
  n8n_protocol: list(http|https)
  n8n_log_level: list(silent|error|warn|info|debug)?
  db_sqlite_pool_size: int?
  env_vars_list:
    - "match(^[A-Z_0-9.]+: .*$)?"
  cmd_line_args: str?